spring:
  application:
    name: book-recommendation-app
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update